from pymongo import MongoClient


client = MongoClient("mongodb+srv://User:1234@cluster0.ybcvjqj.mongodb.net/")

db = client["Herencia"]
collection = db["Persona"]


collection.delete_many({}) 


mock_data = [
  { "name": "Cyberpunk 2077", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/cyberpunk.jpg" },
  { "name": "Elden Ring", "category": "Videojuego", "price": 69.99, "imageUrl": "/images/elden-ring.jpg" },
  { "name": "Dune", "category": "Pelicula", "price": 19.99, "imageUrl": "/images/dune.jpg" },
  { "name": "Oppenheimer", "category": "Pelicula", "price": 22.99, "imageUrl": "/images/oppenheimer.jpg" },
  { "name": "One Piece", "category": "Serie", "price": 10.99, "imageUrl": "/images/one-piece.jpg" },
  { "name": "Peacemaker", "category": "Serie", "price": 17.99, "imageUrl": "/images/peacemaker.jpg" },
  { "name": "Grand Theft Auto V", "category": "Videojuego", "price": 29.99, "imageUrl": "/images/gta-v.jpg" },
  { "name": "The Witcher 3: Wild Hunt", "category": "Videojuego", "price": 39.99, "imageUrl": "/images/witcher-3.jpg" },
  { "name": "Red Dead Redemption 2", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/red-dead-redemption-2.jpg" },
  { "name": "God of War Ragnarok", "category": "Videojuego", "price": 69.99, "imageUrl": "/images/god-of-war-ragnarok.jpg" },
  { "name": "The Last of Us Part I", "category": "Videojuego", "price": 69.99, "imageUrl": "/images/the-last-of-us-part-1.jpg" },
  { "name": "Halo: Combat Evolved", "category": "Videojuego", "price": 9.99, "imageUrl": "/images/halo-combat-evolved.jpg" },
  { "name": "Metal Gear Solid 3", "category": "Videojuego", "price": 19.99, "imageUrl": "/images/mgs-3-snake-eater.jpg" },
  { "name": "Resident Evil 4 Remake", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/resident-evil-4-remake.jpg" },
  { "name": "Minecraft", "category": "Videojuego", "price": 29.99, "imageUrl": "/images/minecraft.jpg" },
  { "name": "Dark Souls III", "category": "Videojuego", "price": 39.99, "imageUrl": "/images/dark-souls-3.jpg" },
  { "name": "Bloodborne", "category": "Videojuego", "price": 19.99, "imageUrl": "/images/bloodborne.jpg" },
  { "name": "Persona 5 Royal", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/persona-5-royal.jpg" },
  { "name": "BioShock", "category": "Videojuego", "price": 14.99, "imageUrl": "/images/bioshock.jpg" },
  { "name": "Mass Effect Legendary Edition", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/mass-effect-legendary.jpg" },
  { "name": "Portal 2", "category": "Videojuego", "price": 9.99, "imageUrl": "/images/portal-2.jpg" },
  { "name": "Hollow Knight", "category": "Videojuego", "price": 14.99, "imageUrl": "/images/hollow-knight.jpg" },
  { "name": "Baldur's Gate 3", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/baldurs-gate-3.jpg" },
  { "name": "Skyrim Anniversary Edition", "category": "Videojuego", "price": 39.99, "imageUrl": "/images/skyrim.jpg" },
  { "name": "Hades", "category": "Videojuego", "price": 24.99, "imageUrl": "/images/hades.jpg" },
  { "name": "Sekiro: Shadows Die Twice", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/sekiro.jpg" },
  { "name": "Dune: Part Two", "category": "Pelicula", "price": 24.99, "imageUrl": "/images/dune-part-two.jpg" },
  { "name": "Spider-Man: Across the Spider-Verse", "category": "Pelicula", "price": 19.99, "imageUrl": "/images/spider-man-spider-verse.jpg" },
  { "name": "The Batman", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/the-batman.jpg" },
  { "name": "Barbie", "category": "Pelicula", "price": 19.99, "imageUrl": "/images/barbie.jpg" },
  { "name": "Guardians of the Galaxy Vol. 3", "category": "Pelicula", "price": 21.99, "imageUrl": "/images/guardians-vol-3.jpg" },
  { "name": "Avatar: The Way of Water", "category": "Pelicula", "price": 19.99, "imageUrl": "/images/avatar-way-of-water.jpg" },
  { "name": "Top Gun: Maverick", "category": "Pelicula", "price": 19.99, "imageUrl": "/images/top-gun-maverick.jpg" },
  { "name": "Everything Everywhere All At Once", "category": "Pelicula", "price": 15.99, "imageUrl": "/images/everything-everywhere.jpg" },
  { "name": "Deadpool & Wolverine", "category": "Pelicula", "price": 29.99, "imageUrl": "/images/deadpool-wolverine.jpg" },
  { "name": "Furiosa: A Mad Max Saga", "category": "Pelicula", "price": 24.99, "imageUrl": "/images/furiosa.jpg" },
  { "name": "The Last of Us", "category": "Serie", "price": 24.99, "imageUrl": "/images/serie-the-last-of-us.jpg" },
  { "name": "House of the Dragon", "category": "Serie", "price": 22.99, "imageUrl": "/images/house-of-the-dragon.jpg" },
  { "name": "The Boys", "category": "Serie", "price": 19.99, "imageUrl": "/images/the-boys.jpg" },
  { "name": "Fallout", "category": "Serie", "price": 21.99, "imageUrl": "/images/serie-fallout.jpg" },
  { "name": "Stranger Things", "category": "Serie", "price": 19.99, "imageUrl": "/images/stranger-things.jpg" },
  { "name": "Succession", "category": "Serie", "price": 24.99, "imageUrl": "/images/succession.jpg" },
  { "name": "The Bear", "category": "Serie", "price": 18.99, "imageUrl": "/images/the-bear.jpg" },
  { "name": "Shogun", "category": "Serie", "price": 25.99, "imageUrl": "/images/shogun.jpg" },
  { "name": "Arcane", "category": "Serie", "price": 19.99, "imageUrl": "/images/arcane.jpg" },
  { "name": "Better Call Saul", "category": "Serie", "price": 29.99, "imageUrl": "/images/better-call-saul.jpg" },
  { "name": "Dragon Ball Z", "category": "Anime", "price": 15.99, "imageUrl": "/images/dragon-ball-z.jpg" },
  { "name": "Saint Seiya", "category": "Anime", "price": 14.99, "imageUrl": "/images/saint-seiya.jpg" },
  { "name": "Neon Genesis Evangelion", "category": "Anime", "price": 24.99, "imageUrl": "/images/evangelion.jpg" },
  { "name": "Cowboy Bebop", "category": "Anime", "price": 19.99, "imageUrl": "/images/cowboy-bebop.jpg" },
  { "name": "Sailor Moon", "category": "Anime", "price": 12.99, "imageUrl": "/images/sailor-moon.jpg" },
  { "name": "Naruto Shippuden", "category": "Anime", "price": 19.99, "imageUrl": "/images/naruto-shippuden.jpg" },
  { "name": "Fullmetal Alchemist: Brotherhood", "category": "Anime", "price": 29.99, "imageUrl": "/images/fma-brotherhood.jpg" },
  { "name": "Death Note", "category": "Anime", "price": 14.99, "imageUrl": "/images/death-note.jpg" },
  { "name": "Attack on Titan", "category": "Anime", "price": 29.99, "imageUrl": "/images/attack-on-titan.jpg" },
  { "name": "Demon Slayer", "category": "Anime", "price": 24.99, "imageUrl": "/images/demon-slayer.jpg" },
  { "name": "Jujutsu Kaisen", "category": "Anime", "price": 24.99, "imageUrl": "/images/jujutsu-kaisen.jpg" },
  { "name": "Chainsaw Man", "category": "Anime", "price": 21.99, "imageUrl": "/images/chainsaw-man.jpg" },
  { "name": "One Punch Man", "category": "Anime", "price": 19.99, "imageUrl": "/images/one-punch-man.jpg" },
  { "name": "Spy x Family", "category": "Anime", "price": 18.99, "imageUrl": "/images/spy-x-family.jpg" },
  { "name": "Frieren: Beyond Journey's End", "category": "Anime", "price": 22.99, "imageUrl": "/images/frieren.jpg" },
  { "name": "Ranma 1/2", "category": "Anime", "price": 14.99, "imageUrl": "/images/ranma.jpg" },
  { "name": "Yu Yu Hakusho", "category": "Anime", "price": 16.99, "imageUrl": "/images/yu-yu-hakusho.jpg" },
  { "name": "Hunter x Hunter", "category": "Anime", "price": 29.99, "imageUrl": "/images/hunter-x-hunter.jpg" },
  { "name": "Akira", "category": "Anime", "price": 19.99, "imageUrl": "/images/akira.jpg" },
  { "name": "Spirited Away", "category": "Anime", "price": 19.99, "imageUrl": "/images/spirited-away.jpg" },
  { "name": "The Legend of Zelda: Tears of the Kingdom", "category": "Videojuego", "price": 69.99, "imageUrl": "/images/zelda-tears-kingdom.jpg" },
  { "name": "Super Mario Bros. Wonder", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/super-mario-wonder.jpg" },
  { "name": "Metroid Prime 4: Beyond", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/metroid-prime-4.jpg" },
  { "name": "Pokémon Legends: Z-A", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/pokemon-legends-z-a.jpg" },
  { "name": "Mario Kart 8 Deluxe", "category": "Videojuego", "price": 49.99, "imageUrl": "/images/mario-kart-8-deluxe.jpg" },
  { "name": "Splatoon 3", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/splatoon-3.jpg" },
  { "name": "Animal Crossing: New Horizons", "category": "Videojuego", "price": 49.99, "imageUrl": "/images/animal-crossing-new-horizons.jpg" },
  { "name": "Xenoblade Chronicles 3", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/xenoblade-chronicles-3.jpg" },
  { "name": "Kirby and the Forgotten Land", "category": "Videojuego", "price": 49.99, "imageUrl": "/images/kirby-forgotten-land.jpg" },
  { "name": "Fire Emblem Engage", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/fire-emblem-engage.jpg" },
  { "name": "Super Smash Bros. Ultimate", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/smash-bros-ultimate.jpg" },
  { "name": "Luigi's Mansion 3", "category": "Videojuego", "price": 49.99, "imageUrl": "/images/luigis-mansion-3.jpg" },
  { "name": "Donkey Kong Country Returns HD", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/donkey-kong-returns-hd.jpg" },
  { "name": "Princess Peach: Showtime!", "category": "Videojuego", "price": 49.99, "imageUrl": "/images/princess-peach-showtime.jpg" },
  { "name": "Paper Mario: The Thousand-Year Door", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/paper-mario-ttyd.jpg" },
  { "name": "Pikmin 4", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/pikmin-4.jpg" }, #checkpoint
  { "name": "Bayonetta 3", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/bayonetta-3.jpg" },
  { "name": "Astral Chain", "category": "Videojuego", "price": 49.99, "imageUrl": "/images/astral-chain.jpg" },
  { "name": "Mario + Rabbids Sparks of Hope", "category": "Videojuego", "price": 29.99, "imageUrl": "/images/mario-rabbids-sparks.jpg" },
  { "name": "Monster Hunter Rise: Sunbreak", "category": "Videojuego", "price": 39.99, "imageUrl": "/images/monster-hunter-rise.jpg" },
  { "name": "Shin Megami Tensei V: Vengeance", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/smt-v-vengeance.jpg" },
  { "name": "The Legend of Zelda: Echoes of Wisdom", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/zelda-echoes-wisdom.jpg" },
  { "name": "Mario & Luigi: Brothership", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/mario-luigi-brothership.jpg" },
  { "name": "Hollow Knight: Silksong", "category": "Videojuego", "price": 29.99, "imageUrl": "/images/hollow-knight-silksong.jpg" },
  { "name": "Hades II", "category": "Videojuego", "price": 29.99, "imageUrl": "/images/hades-ii.jpg" },
  { "name": "Professor Layton and the New World of Steam", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/professor-layton-new-world.jpg" },
  { "name": "Dragon Quest III HD-2D Remake", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/dragon-quest-iii-hd2d.jpg" },
  { "name": "Inside Out 2", "category": "Pelicula", "price": 24.99, "imageUrl": "/images/inside-out-2.jpg" },
  { "name": "The Wild Robot", "category": "Pelicula", "price": 19.99, "imageUrl": "/images/the-wild-robot.jpg" },
  { "name": "Kung Fu Panda 4", "category": "Pelicula", "price": 19.99, "imageUrl": "/images/kung-fu-panda-4.jpg" },
  { "name": "The Super Mario Bros. Movie", "category": "Pelicula", "price": 19.99, "imageUrl": "/images/super-mario-bros-movie.jpg" },
  { "name": "Puss in Boots: The Last Wish", "category": "Pelicula", "price": 18.99, "imageUrl": "/images/puss-in-boots-last-wish.jpg" },
  { "name": "Teenage Mutant Ninja Turtles: Mutant Mayhem", "category": "Pelicula", "price": 19.99, "imageUrl": "/images/tmnt-mutant-mayhem.jpg" },
  { "name": "Nimona", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/nimona.jpg" },
  { "name": "Guillermo del Toro's Pinocchio", "category": "Pelicula", "price": 19.99, "imageUrl": "/images/gdt-pinocchio.jpg" },
  { "name": "Elemental", "category": "Pelicula", "price": 19.99, "imageUrl": "/images/elemental.jpg" },
  { "name": "Encanto", "category": "Pelicula", "price": 15.99, "imageUrl": "/images/encanto.jpg" },
  { "name": "Soul", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/soul.jpg" },
  { "name": "Luca", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/luca.jpg" },
  { "name": "Turning Red", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/turning-red.jpg" },
  { "name": "The Boy and the Heron", "category": "Pelicula", "price": 24.99, "imageUrl": "/images/boy-and-the-heron.jpg" },
  { "name": "Suzume", "category": "Pelicula", "price": 21.99, "imageUrl": "/images/suzume.jpg" }, #checkpoint
  { "name": "Your Name", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/your-name.jpeg" },
  { "name": "Weathering With You", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/weathering-with-you.jpg" },
  { "name": "A Silent Voice", "category": "Pelicula", "price": 12.99, "imageUrl": "/images/a-silent-voice.jpeg" },# check
  { "name": "Marcel the Shell with Shoes On", "category": "Pelicula", "price": 16.99, "imageUrl": "/images/marcel-shell.jpg" },
  { "name": "Robot Dreams", "category": "Pelicula", "price": 18.99, "imageUrl": "/images/robot-dreams.jpg" },
  { "name": "Migration", "category": "Pelicula", "price": 19.99, "imageUrl": "/images/migration.jpg" },
  { "name": "Minions: The Rise of Gru", "category": "Pelicula", "price": 15.99, "imageUrl": "/images/minions-rise-of-gru.jpg" },
  { "name": "Arcane Season 2", "category": "Serie", "price": 24.99, "imageUrl": "/images/arcane-s2.jpg" },
  { "name": "Blue Eye Samurai", "category": "Serie", "price": 19.99, "imageUrl": "/images/blue-eye-samurai.jpg" },
  { "name": "Hazbin Hotel", "category": "Serie", "price": 21.99, "imageUrl": "/images/hazbin-hotel.jpg" },
  { "name": "X-Men '97", "category": "Serie", "price": 24.99, "imageUrl": "/images/x-men-97.jpg" },
  { "name": "Invincible Season 2", "category": "Serie", "price": 22.99, "imageUrl": "/images/invincible-s2.jpg" },
  { "name": "The Legend of Vox Machina", "category": "Serie", "price": 19.99, "imageUrl": "/images/vox-machina.jpg" },
  { "name": "Rick and Morty", "category": "Serie", "price": 19.99, "imageUrl": "/images/rick-and-morty.jpg" },
  { "name": "Love, Death & Robots", "category": "Serie", "price": 24.99, "imageUrl": "/images/love-death-robots.jpg" },
  { "name": "Cyberpunk: Edgerunners", "category": "Serie", "price": 29.99, "imageUrl": "/images/cyberpunk-edgerunners.jpg" },
  { "name": "Castlevania: Nocturne", "category": "Serie", "price": 19.99, "imageUrl": "/images/castlevania-nocturne.jpg" },
  { "name": "Scavengers Reign", "category": "Serie", "price": 21.99, "imageUrl": "/images/scavengers-reign.jpg" },
  { "name": "My Adventures with Superman", "category": "Serie", "price": 18.99, "imageUrl": "/images/my-adventures-superman.jpg" },
  { "name": "Harley Quinn", "category": "Serie", "price": 19.99, "imageUrl": "/images/harley-quinn-animated.jpg" },
  { "name": "The Owl House", "category": "Serie", "price": 14.99, "imageUrl": "/images/owl-house.jpg" },
  { "name": "Amphibia", "category": "Serie", "price": 14.99, "imageUrl": "/images/amphibia.jpg" },
  { "name": "Gravity Falls", "category": "Serie", "price": 14.99, "imageUrl": "/images/gravity-falls.jpg" },
  { "name": "Avatar: The Last Airbender", "category": "Serie", "price": 19.99, "imageUrl": "/images/avatar-last-airbender.jpg" },
  { "name": "The Legend of Korra", "category": "Serie", "price": 19.99, "imageUrl": "/images/legend-of-korra.jpg" },
  { "name": "Star Wars: The Clone Wars", "category": "Serie", "price": 29.99, "imageUrl": "/images/clone-wars.jpg" },
  { "name": "Star Wars: The Bad Batch", "category": "Serie", "price": 24.99, "imageUrl": "/images/bad-batch.jpg" },
  { "name": "Delicious in Dungeon", "category": "Anime", "price": 24.99, "imageUrl": "/images/delicious-in-dungeon.jpg" },
  { "name": "Kaiju No. 8", "category": "Anime", "price": 21.99, "imageUrl": "/images/kaiju-no-8.jpg" },
  { "name": "Solo Leveling", "category": "Anime", "price": 22.99, "imageUrl": "/images/solo-leveling.jpg" },
  { "name": "Hell's Paradise", "category": "Anime", "price": 19.99, "imageUrl": "/images/hells-paradise.jpg" },
  { "name": "Mashle: Magic and Muscles", "category": "Anime", "price": 18.99, "imageUrl": "/images/mashle.jpg" },
  { "name": "Bleach: Thousand-Year Blood War", "category": "Anime", "price": 29.99, "imageUrl": "/images/bleach-tybw.jpg" },
  { "name": "Vinland Saga Season 2", "category": "Anime", "price": 24.99, "imageUrl": "/images/vinland-saga-s2.jpg" },
  { "name": "Mob Psycho 100 III", "category": "Anime", "price": 24.99, "imageUrl": "/images/mob-psycho-100.jpg" },
  { "name": "Pluto", "category": "Anime", "price": 24.99, "imageUrl": "/images/pluto.jpg" },
  { "name": "Cyberpunk: Edgerunners", "category": "Anime", "price": 29.99, "imageUrl": "/images/cyberpunk-edgerunners.jpg" },
  { "name": "Trigun Stampede", "category": "Anime", "price": 19.99, "imageUrl": "/images/trigun-stampede.jpg" },
  { "name": "Blue Lock", "category": "Anime", "price": 21.99, "imageUrl": "/images/blue-lock.jpg" },
  { "name": "Oshi no Ko", "category": "Anime", "price": 22.99, "imageUrl": "/images/oshi-no-ko.jpg" },
  { "name": "Zom 100: Bucket List of the Dead", "category": "Anime", "price": 19.99, "imageUrl": "/images/zom-100.jpg" },
  { "name": "Dr. Stone: New World", "category": "Anime", "price": 24.99, "imageUrl": "/images/dr-stone-new-world.jpg" },
  { "name": "JoJo's Bizarre Adventure: Stone Ocean", "category": "Anime", "price": 29.99, "imageUrl": "/images/jojo-stone-ocean.jpg" },
  { "name": "Made in Abyss", "category": "Anime", "price": 24.99, "imageUrl": "/images/made-in-abyss.jpg" },
  { "name": "Violet Evergarden", "category": "Anime", "price": 19.99, "imageUrl": "/images/violet-evergarden.jpg" },
  { "name": "Haikyuu!!", "category": "Anime", "price": 24.99, "imageUrl": "/images/haikyuu.jpg" },
  { "name": "The Apothecary Diaries", "category": "Anime", "price": 21.99, "imageUrl": "/images/apothecary-diaries.jpg" },
  { "name": "Ranking of Kings", "category": "Anime", "price": 19.99, "imageUrl": "/images/ranking-of-kings.jpg" },
  { "name": "Mobile Suit Gundam: The Witch from Mercury", "category": "Anime", "price": 24.99, "imageUrl": "/images/gundam-witch-mercury.jpg" },
  { "name": "Super Mario Party Jamboree", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/mario-party-jamboree.jpg" },
  { "name": "Metroid Dread", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/metroid-dread.jpg" },
  { "name": "The Legend of Zelda: Link's Awakening", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/zelda-links-awakening.jpg" },
  { "name": "Pokémon Scarlet & Violet", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/pokemon-scarlet-violet.jpg" },
  { "name": "Pokémon Legends: Arceus", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/pokemon-legends-arceus.jpg" },
  { "name": "Super Mario 3D World + Bowser's Fury", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/mario-3d-world.jpg" },
  { "name": "Paper Mario: The Origami King", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/paper-mario-origami-king.jpg" },
  { "name": "Yoshi's Crafted World", "category": "Videojuego", "price": 49.99, "imageUrl": "/images/yoshis-crafted-world.jpg" },
  { "name": "Donkey Kong Country: Tropical Freeze", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/dk-tropical-freeze.jpg" },
  { "name": "Captain Toad: Treasure Tracker", "category": "Videojuego", "price": 39.99, "imageUrl": "/images/captain-toad.jpg" },
  { "name": "Fire Emblem: Three Houses", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/fire-emblem-three-houses.jpg" },
  { "name": "Xenoblade Chronicles: Definitive Edition", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/xenoblade-chronicles-de.jpg" },
  { "name": "Xenoblade Chronicles 2", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/xenoblade-chronicles-2.jpg" },
  { "name": "Octopath Traveler II", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/octopath-traveler-2.jpg" },
  { "name": "Triangle Strategy", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/triangle-strategy.jpg" },
  { "name": "Live A Live", "category": "Videojuego", "price": 49.99, "imageUrl": "/images/live-a-live.jpg" },
  { "name": "Bravely Default II", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/bravely-default-2.jpg" },
  { "name": "Monster Hunter Stories 2: Wings of Ruin", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/mh-stories-2.jpg" },
  { "name": "The Legend of Zelda: Skyward Sword HD", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/zelda-skyward-sword-hd.jpg" },
  { "name": "Pikmin 1+2 Bundle", "category": "Videojuego", "price": 49.99, "imageUrl": "/images/pikmin-1-2-bundle.jpg" },
  { "name": "WarioWare: Move It!", "category": "Videojuego", "price": 49.99, "imageUrl": "/images/warioware-move-it.jpg" },
  { "name": "Advance Wars 1+2: Re-Boot Camp", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/advance-wars-reboot.jpg" },
  { "name": "Kirby's Return to Dream Land Deluxe", "category": "Videojuego", "price": 59.99, "imageUrl": "/images/kirby-return-dreamland.jpg" },
  { "name": "Layton's Mystery Journey", "category": "Videojuego", "price": 39.99, "imageUrl": "/images/laytons-mystery-journey.jpg" },
  { "name": "Ace Attorney Investigations Collection", "category": "Videojuego", "price": 39.99, "imageUrl": "/images/ace-attorney-investigations.jpg" },
  { "name": "Toy Story", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/toy-story.jpg" },
  { "name": "Toy Story 2", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/toy-story-2.jpg" },
  { "name": "Toy Story 3", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/toy-story-3.jpg" },
  { "name": "The Incredibles", "category": "Pelicula", "price": 15.99, "imageUrl": "/images/the-incredibles.jpg" },
  { "name": "Finding Nemo", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/finding-nemo.jpg" },
  { "name": "Monsters, Inc.", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/monsters-inc.jpg" },
  { "name": "WALL-E", "category": "Pelicula", "price": 15.99, "imageUrl": "/images/wall-e.jpg" },
  { "name": "Up", "category": "Pelicula", "price": 15.99, "imageUrl": "/images/up.jpg" },
  { "name": "Ratatouille", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/ratatouille.jpg" },
  { "name": "Coco", "category": "Pelicula", "price": 16.99, "imageUrl": "/images/coco.jpg" },
  { "name": "Shrek", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/shrek.jpg" },
  { "name": "Shrek 2", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/shrek-2.jpg" },
  { "name": "Kung Fu Panda", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/kung-fu-panda.jpg" },
  { "name": "How to Train Your Dragon", "category": "Pelicula", "price": 15.99, "imageUrl": "/images/how-to-train-your-dragon.jpg" },
  { "name": "Madagascar", "category": "Pelicula", "price": 12.99, "imageUrl": "/images/madagascar.jpg" },
  { "name": "Megamind", "category": "Pelicula", "price": 13.99, "imageUrl": "/images/megamind.jpg" },
  { "name": "Rise of the Guardians", "category": "Pelicula", "price": 12.99, "imageUrl": "/images/rise-of-the-guardians.jpg" },
  { "name": "Coraline", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/coraline.jpg" },
  { "name": "Kubo and the Two Strings", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/kubo-two-strings.jpg" },
  { "name": "Isle of Dogs", "category": "Pelicula", "price": 15.99, "imageUrl": "/images/isle-of-dogs.jpg" },
  { "name": "Fantastic Mr. Fox", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/fantastic-mr-fox.jpg" },
  { "name": "The Nightmare Before Christmas", "category": "Pelicula", "price": 14.99, "imageUrl": "/images/nightmare-before-christmas.jpg" },
  { "name": "The Iron Giant", "category": "Pelicula", "price": 12.99, "imageUrl": "/images/iron-giant.jpg" },
  { "name": "Chicken Run", "category": "Pelicula", "price": 12.99, "imageUrl": "/images/chicken-run.jpg" },
  { "name": "Wallace & Gromit: The Curse of the Were-Rabbit", "category": "Pelicula", "price": 13.99, "imageUrl": "/images/wallace-gromit.jpg" },
  { "name": "SpongeBob SquarePants", "category": "Serie", "price": 19.99, "imageUrl": "/images/spongebob.jpg" },
  { "name": "The Fairly OddParents", "category": "Serie", "price": 14.99, "imageUrl": "/images/fairly-oddparents.jpg" },
  { "name": "Danny Phantom", "category": "Serie", "price": 15.99, "imageUrl": "/images/danny-phantom.jpg" },
  { "name": "Jimmy Neutron: Boy Genius", "category": "Serie", "price": 14.99, "imageUrl": "/images/jimmy-neutron.jpg" },
  { "name": "Adventure Time", "category": "Serie", "price": 24.99, "imageUrl": "/images/adventure-time.jpg" },
  { "name": "Regular Show", "category": "Serie", "price": 24.99, "imageUrl": "/images/regular-show.jpg" },
  { "name": "Steven Universe", "category": "Serie", "price": 19.99, "imageUrl": "/images/steven-universe.jpg" },
  { "name": "The Amazing World of Gumball", "category": "Serie", "price": 19.99, "imageUrl": "/images/gumball.jpg" },
  { "name": "Ben 10 (Classic)", "category": "Serie", "price": 19.99, "imageUrl": "/images/ben-10.jpg" },
  { "name": "Teen Titans", "category": "Serie", "price": 19.99, "imageUrl": "/images/teen-titans.jpg" },
  { "name": "Samurai Jack", "category": "Serie", "price": 24.99, "imageUrl": "/images/samurai-jack.jpg" },
  { "name": "The Powerpuff Girls", "category": "Serie", "price": 14.99, "imageUrl": "/images/powerpuff-girls.jpg" },
  { "name": "Dexter's Laboratory", "category": "Serie", "price": 14.99, "imageUrl": "/images/dexters-lab.jpg" },
  { "name": "Courage the Cowardly Dog", "category": "Serie", "price": 14.99, "imageUrl": "/images/courage-cowardly-dog.jpg" },
  { "name": "Ed, Edd n Eddy", "category": "Serie", "price": 14.99, "imageUrl": "/images/ed-edd-n-eddy.jpg" },
  { "name": "Phineas and Ferb", "category": "Serie", "price": 19.99, "imageUrl": "/images/phineas-and-ferb.jpg" },
  { "name": "Kim Possible", "category": "Serie", "price": 15.99, "imageUrl": "/images/kim-possible.jpg" },
  { "name": "American Dragon: Jake Long", "category": "Serie", "price": 14.99, "imageUrl": "/images/american-dragon.jpg" },
  { "name": "Recess", "category": "Serie", "price": 12.99, "imageUrl": "/images/recess.jpg" },
  { "name": "Gargoyles", "category": "Serie", "price": 19.99, "imageUrl": "/images/gargoyles.jpg" },
  { "name": "Captain Tsubasa", "category": "Anime", "price": 14.99, "imageUrl": "/images/captain-tsubasa.jpg" },
  { "name": "Knights of the Zodiac (Saint Seiya)", "category": "Anime", "price": 19.99, "imageUrl": "/images/knights-zodiac.jpg" },
  { "name": "Mazinger Z", "category": "Anime", "price": 14.99, "imageUrl": "/images/mazinger-z.jpg" },
  { "name": "Robotech", "category": "Anime", "price": 19.99, "imageUrl": "/images/robotech.jpg" },
  { "name": "Voltron", "category": "Anime", "price": 14.99, "imageUrl": "/images/voltron.jpg" },
  { "name": "Astro Boy (1980)", "category": "Anime", "price": 12.99, "imageUrl": "/images/astro-boy.jpg" },
  { "name": "Speed Racer", "category": "Anime", "price": 12.99, "imageUrl": "/images/speed-racer.jpg" },
  { "name": "Candy Candy", "category": "Anime", "price": 14.99, "imageUrl": "/images/candy-candy.jpg" },
  { "name": "Heidi, Girl of the Alps", "category": "Anime", "price": 14.99, "imageUrl": "/images/heidi.jpg" },
  { "name": "Rose of Versailles", "category": "Anime", "price": 19.99, "imageUrl": "/images/rose-of-versailles.jpg" },
  { "name": "Slam Dunk", "category": "Anime", "price": 19.99, "imageUrl": "/images/slam-dunk.jpg" },
  { "name": "Rurouni Kenshin", "category": "Anime", "price": 19.99, "imageUrl": "/images/rurouni-kenshin.jpg" },
  { "name": "Inuyasha", "category": "Anime", "price": 24.99, "imageUrl": "/images/inuyasha.jpg" }, #fin
  { "name": "Digimon Adventure", "category": "Anime", "price": 19.99, "imageUrl": "/images/digimon-adventure.jpg" },
  { "name": "Pokémon (Indigo League)", "category": "Anime", "price": 19.99, "imageUrl": "/images/pokemon-anime.jpg" },
  { "name": "Yu-Gi-Oh! Duel Monsters", "category": "Anime", "price": 19.99, "imageUrl": "/images/yugioh.jpg" },
  { "name": "Cardcaptor Sakura", "category": "Anime", "price": 19.99, "imageUrl": "/images/cardcaptor-sakura.jpg" },
  { "name": "Beyblade", "category": "Anime", "price": 14.99, "imageUrl": "/images/beyblade.jpg" },
  { "name": "Medabots", "category": "Anime", "price": 14.99, "imageUrl": "/images/medabots.jpg" },
  { "name": "Zatch Bell!", "category": "Anime", "price": 14.99, "imageUrl": "/images/zatch-bell.jpg" },
  { "name": "Shaman King (2001)", "category": "Anime", "price": 19.99, "imageUrl": "/images/shaman-king.jpg" },
  { "name": "Hellsing", "category": "Anime", "price": 19.99, "imageUrl": "/images/hellsing.jpg" },
  { "name": "Great Teacher Onizuka", "category": "Anime", "price": 24.99, "imageUrl": "/images/gto.jpg" },
  { "name": "Serial Experiments Lain", "category": "Anime", "price": 19.99, "imageUrl": "/images/lain.jpg" },
  { "name": "FLCL", "category": "Anime", "price": 19.99, "imageUrl": "/images/flcl.jpg" }
]
# Inserta los datos
result = collection.insert_many(mock_data)

print(f"Se insertaron {len(result.inserted_ids)} documentos en la colección 'productos'.")
print("¡Base de datos lista!")